spring:
  datasource:
    url: jdbc:mysql://database-1.c5u0yi6swiin.ap-northeast-2.rds.amazonaws.com:3306/testdb
    username: admin
    password: Harun!17301730
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # ???: create / update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
jwt:
  secret:
    key: hjksdfhgklfadshgfdsd45fdsgfsdgsfdghdfgshsgf66adfgfadg8sdg4df22fasdgdas